import PolicyPage from '../components/PolicyPage'

const sections = [
  { title: 'A. Working Hours, Leave & Dress Code', clauses: ['The Company is engaged in providing products and other services to its customers. Working hours and leave must align with operational requirements. Any changes will be notified from time to time.', 'Working hours shall be 09:00 am to 06:00 pm on each working day, Monday to Saturday. Your Reporting Authority may change these hours to suit the needs of the Company.', 'Exceptions and flexibility for working hours, leave and holidays may be required to meet customer or project needs. In such cases, prior written intimation to or approval from your Reporting Authority is necessary.', 'Employees are expected to dress modestly and professionally in accordance with workplace standards.'] },
  { title: 'B. Intellectual Property, Trade Secrets & Confidentiality', clauses: ['Any invention, process improvement, operational improvement or method created during your employment that relates to Company activity shall vest in the Company, subject to applicable law. The Company may use it for patent rights or any other purpose.', 'You must maintain strict confidentiality regarding all technical, business and proprietary information acquired during employment, including products, systems, software and customer-related data. This obligation continues after employment ends.', 'You shall treat the affairs of the Company and its customers as strictly confidential, including products, quotations, specifications, trade secrets, systems, procedures and policy information.', 'On joining the Company, you shall execute the applicable agreement covering non-disclosure of confidential information and vesting of intellectual property rights developed during employment in the name of the Company.', 'Without prior written Company approval, you shall not author or contribute to any publication, article, blog or report relating to the business, products, technology, strategy or operations of P.L. Robotics Pvt. Ltd., including on public platforms and social media.'] },
  { title: 'C. Access to Company Intellectual Property', clauses: ['You may be required to use Company intellectual property or confidential information, including trade secrets, patents, proprietary software, designs and business data. You must acknowledge in writing any statement of the technology or information you are required to use or develop before access is provided.', 'When your employment ends, you shall stop using and return or securely delete Company intellectual property and confidential information as instructed by the Company.'] },
  { title: 'D. Reimbursements', clauses: ['Any expense incurred on behalf of the Company must first be approved by your Reporting Authority. Authorised expenses borne by you will be reimbursed upon submission of valid proof in accordance with Company procedures.'] },
  { title: 'E. End of Employment', clauses: ['Your notice period, termination process and final working date are governed by the employment agreement issued to you by the Company and applicable law.'] },
  { title: 'F. Employee Confidentiality Agreement', clauses: ['Confidential Information means data or information unique to the Company, proprietary, competitively sensitive and not generally known by the public. It includes business, customer, supplier, product, financial, employee, operational, administrative and contract information, but excludes information publicly available through no breach of this Agreement.', 'Confidential Information must not be shared with any parent, spouse, sibling, child, child-in-law, other family member or friend unless the Company has given prior written consent.', 'You shall take reasonable care to protect Confidential Information, use it solely to perform your employment duties, and not disclose it without prior written Company consent.', 'These obligations survive termination. On termination, you shall return all Confidential Information in your possession and retain no copy.', 'A violation may result in termination of services and civil or criminal action, damages or other remedies available under applicable law. If any provision is unenforceable, the remaining provisions continue to apply. Courts at Washim shall have jurisdiction, subject to applicable law.'] },
]

export default function EmployeePolicies() {
  return <PolicyPage audience="Employee" description="Please read these policies carefully. They describe the working expectations, confidentiality responsibilities, intellectual property provisions, reimbursements and end-of-employment terms applicable to employees at P.L. Robotics Pvt. Ltd." sections={sections} otherPolicy={{ path: '/intern-policies', label: 'Intern Policies' }} />
}
